[tool.black]
line-length = 119


[tool.flake8]
max-line-length = 119
ignore = ["E203"]

[tool.pylint.format]
max-line-length = 119

[tool.pylint.design]
max-args = 10 # Maximum number of arguments for a function

[tool.pylint.messages_control]
disable = [
    "logging-fstring-interpolation", # Ignore logging f-string interpolation warnings
    "too-many-positional-arguments", # Disable positional arguments limit warning
    "broad-exception-caught"        # Disable broad exception warnings
]
